name: Deploy
on:
  push:
    branches:
      - webapp__dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.FOLDER }}/${{ github.ref_name }}
            sudo git pull

            # install dependencies
            yarn

            # Créer un fichier .env et y ajouter les secrets

            case ${{ github.ref_name }} in
              webapp__dev)
                ENV_FILE_CONTENT="${{ secrets.WEBAPP__DEV_ENV_FILE }}";;
              *)
              ENV_FILE_CONTENT="";;
            esac

            sudo rm -f .env
            echo "$ENV_FILE_CONTENT" > .env

            # build
            yarn build

            sudo systemctl restart ${{ github.ref_name }}.digibank.service
